# Generated by Django 5.0.1 on 2024-02-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_checkoutadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutadd',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
